# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /Update Readme and Manifest Version/

environment:
  access_token:
    secure: EJ2HHF0klBsYS3WlZWIvcc88u5/gixju8bcOR4d13x6Fh+BA7UNU89/NPkHYP6JN

## branches to build
#branches:
#  # whitelist
#  only:
#  #  - master
#    - dev

# build for tags and non tags
skip_tags: false
skip_non_tags: false
    
install:
  - choco install pester


build: false

test_script:
  - ps: $TestResult = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($TestResult.FailedCount -gt 0) { throw "$($Test.FailedCount) tests failed."}
  
  
#on_success:
  # ( Branch specific )

for:

-
  branches:
    only:
      - master 
      
 # on_success:
    # ----- Enable Git Credential Store and add token
 #   - git config --global credential.helper store
 #   - git config --global user.email "jeffbuenting@gmail.com"
 #   - git config --global user.name "jeffbuenting" 
 #   
 #   - ps: $env:APPVEYOR_REPO_BRANCH
 #   - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 #   - ps: $Readme = Get-Content readme.md 
    - ps:   Write-Output "Master Branch"
#  - ps:   # ----- Get Dev version
#  - ps:   $DevVersion = $Readme | Select-String -Pattern "Dev Version: (\d*\.\d*\.\d*)" | foreach { $_.Matches.Groups[1].Value } 
#  - ps:   # ----- Update Readme.md Version number
#  - ps:   $Readme -replace "Master Version: \d*\.\d*\.\d*","Master Version: $DevVersion" | Set-Content README.md
#  - ps:   # ----- Update the module manifests version
#  - ps:   Update-ModuleManifest -Path certificates.psd1 -ModuleVersion $DevVersion
#  - ps: }

-
  branches:
    only:
      - dev
      
 # on_success:

    -ps:    Write-Output "Dev Branch"
#  - ps:   # ----- Update Readme.md Version number
#  - ps:   $Readme -replace "Dev Version: \d*\.\d*\.\d*","Dev Version: $env:APPVEYOR_BUILD_VERSION" | Set-Content README.md
#  - ps:   # ----- Update the module manifests version
#  - ps:   Update-ModuleManifest -Path certificates.psd1 -ModuleVersion $env:APPVEYOR_BUILD_VERSION

#
#  # ----- Push back to Github
#  - git checkout %APPVEYOR_REPO_BRANCH%
#  - git add --all
#  - git status
#  - git commit -s -m "Update Readme and Manifest Version"
#  - git push origin %APPVEYOR_REPO_BRANCH%
  

