# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ jeffbuenting-patch-1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: pester-tests-report
      uses: zyborg/pester-tests-report@v1.3.3
      with:
        include_paths: Tests
