
name: UnitTests
 
on:
  push:
    branches: [ ** ]  # ----- all branches

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - name: pester-tests-report
      uses: zyborg/pester-tests-report@v1.3.3
      with:
        include_paths: Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
