# This is a basic workflow to help you get started with Actions

name: UnitTest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      '**'
  pull_request:
    branches:
      '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pester-test:
    name: Pester test
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: pester-tests-report
        uses: zyborg/pester-tests-report@v1.3.3
        with:
          include_paths: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
  UpdateModuleVersion:
    name: Update Module Version
    needs: pester-test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Update Module Version
        uses: jeffbuenting/UpdateModuleVersion@dev

      - name: Commit
        if: ${{ success() }}
        run: |
          git status
          git config --global user.name 'github actions'      
          git config --global user.email 'actions@github.com'
          git ls-files --others --exclude-standard
          git commit -am "skip ci - Unit Test Version Update"
          git push
