
name: UpdatePSModuleVersion

on:
  push:
    branches: 
      'jeffbuenting-patch-1'
      
  workflow_run:
    workflows: "UnitTest"
    types:
      - completed

  workflow_dispatch:

jobs:

  job1:
    # ----- Only run if UnitTest workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion }} == 'success'
    
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
 
      - uses: jeffbuenting/UpdateModuleVersion@main
